### ISSUE TITLE
plugin not working for windows

### ISSUE THREAD

**Issue by mdangear** [cmacclang/cmacc-vscode#1]
Installed the plugin on a windows machine. tried to preview a doc from the cmacc-test repo. got an error:
Error: ENOENT: no such file or directory, open 'C:\C:\Users\Clémentine\Pictures\Documents\GitHub\cmacc-test\ID\gender\he.cmacc'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:178:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:511:29)
    at fetch (C:\Users\Clémentine\.vscode\extensions\wilmveel.cmacc-vscode-0.0.26\node_modules\cmacc-compiler\src\fetch.js:33:27)
    at convert (C:\Users\Clémentine\.vscode\extensions\wilmveel.cmacc-vscode-0.0.26\node_modules\cmacc-compiler\src\convert.js:17:16)
    at parse (C:\Users\Clémentine\.vscode\extensions\wilmveel.cmacc-vscode-0.0.26\node_modules\cmacc-compiler\src\parse.js:7:23)
    at eval (eval at parse (C:\Users\Clémentine\.vscode\extensions\wilmveel.cmacc-vscode-0.0.26\node_modules\cmacc-compiler\src\parse.js:8:23), :9:14)
    at parse (C:\Users\Clémentine\.vscode\extensions\wilmveel.cmacc-vscode-0.0.26\node_modules\cmacc-compiler\src\parse.js:8:23)

**Comment by mdangear** [comment]
notice the C:\C:\Users at the beginning of the link that the plugin is trying to open. got this on several windows machine.
